//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rFtpSrvCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rFtpSrvCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;FtpDirectory&quot;: &quot;SomeDirectory&quot;,
        ///    &quot;ListenAddress&quot;: &quot;127.0.0.1&quot;,
        ///    &quot;ListenPort&quot;: 21,
        ///    &quot;UsersFile&quot;: &quot;users.json&quot;,
        ///	&quot;PasswordSalt&quot;: &quot;vB9WszRDfyDjL3ZSLwNC6VkHymZiX3rk&quot;,
        ///	&quot;FileSettings&quot;: [
        ///		{
        ///			&quot;Path&quot;: &quot;[.*]*block.txt$&quot;,
        ///			&quot;AllowRegex&quot;: true,
        ///			&quot;BlockAll&quot;: true
        ///		},
        ///		{
        ///			&quot;Path&quot;: &quot;blockedFile.txt&quot;,
        ///			&quot;AllowRegex&quot;: true,
        ///			&quot;BlockList&quot;: true,
        ///			&quot;BlockCreate&quot;: true,
        ///			&quot;BlockDelete&quot;: false,
        ///			&quot;BlockRead&quot;: true,
        ///			&quot;BlockWrite&quot;: true,
        ///			&quot;BlockMove&quot;: true,
        ///			&quot;BlockCopy&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Users&quot;: [
        ///		{
        ///			&quot;Username&quot;: &quot;test&quot;,
        ///			&quot;PasswordHash&quot;: &quot;2AAE6B230C6E4475C72285CADF929147BE9A975498B8F3B667E09DA3A5F9ACC6&quot;
        ///		},
        ///		{
        ///			&quot;Username&quot;: &quot;test2&quot;,
        ///			&quot;PasswordHash&quot;: &quot;0C7AF1AC89F973A46A12FF1B3719A940465B6C851C43D22BEB670A020589C130&quot;
        ///		}
        ///	]
        ///}.
        /// </summary>
        internal static string DefaultUsers {
            get {
                return ResourceManager.GetString("DefaultUsers", resourceCulture);
            }
        }
    }
}
